# Generated by Django 5.0.3 on 2024-04-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("link", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/")),
                ("total_episodes", models.IntegerField()),
                ("current_episode", models.IntegerField()),
                ("current_season", models.IntegerField()),
                ("status", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("link", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/")),
                ("status", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("link", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/")),
                ("total_episodes", models.IntegerField()),
                ("current_episode", models.IntegerField()),
                ("current_season", models.IntegerField()),
                ("status", models.CharField(max_length=100)),
            ],
        ),
    ]
